---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# pacnvegetation

<!-- badges: start -->
<!-- badges: end -->

The goal of pacnvegetation is to provide easy-to-use functions for working with PACN vegetation data.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jakegross808/pacn-veg-package")
```
## Getting started

This package is designed to invisibly load the raw data into memory so that the user doesn't have to keep track of it. To do this, you must call `LoadPACNVeg` any time you call `library(pacnvegetation)`. The package handles the rest! `LoadPACNVeg` invisibly returns a list containing all the raw data if you need it for testing purposes.

By default, `LoadPACNVeg` will cache the data on your local hard drive for 7 days so that you don't have to pull the data over the network every time. Expect it to take a couple minutes to load data from the databases. Loading cached data should only take a few seconds though.

``` r
library(pacnvegetation)
# Change this to point to your EIPS database(s)
access_dbs <- c("path/to/eips_database_1.mdb", "path/to/eips_database_2.mdb", "path/to/eips_database_master.mdb")
# Load the data
LoadPACNVeg(ftpc_params = "pacnveg", eips_paths = access_dbs)
```

## Available functions

For more details, see the documentation.

 - **LoadPACNVeg**: Load the raw data into memory (see above).
 - **WritePACNVeg**: Write data to csv. Provides options to filter data if desired.
 - **PlotAndTransectLocations**: Lat/long coordinates of each plot and transect.
 - **MapPACNVeg**: Map plot and/or transect locations.
 - **UnderNativityCoverTotal**: Calculate understory % cover by nativity.
 - **ClearPACNVegCache**: Clear the data from the cache used by LoadPACNVeg. Typically not needed but useful if you need to free up hard drive space.
 - **FilterPACNVeg**: You can use this to retrieve and optionally filter the raw data. Useful for troubleshooting and preliminary data exploration, but this function is primarily used within other package functions.

## Reporting bugs and requesting new features

Bugs and feature requests can be added as issues here: https://github.com/jakegross808/pacn-veg-package/issues
